### ISSUE TITLE
The search_stack_overflow function does not take the query string as input 

### ISSUE THREAD

**Issue by vedadeva** [naanunaane/semanti-search#1]

**Comment by naanunaane** [comment]
While the function doesn't have the parameter, since it is mapped to a URL path in Flask, we get access to a variable called as request. This lets us access the headers, arguments passed to the REST API GET request. 

![Code taking the "query" key from the request](https://user-images.githubusercontent.com/48794849/117652320-a9704600-b1b0-11eb-9132-38a3aabf73ff.png)

This is how you pass the body through Postman if you are trying to hit your local endpoint.

![Postman Screenshot](https://user-images.githubusercontent.com/48794849/117652558-f227ff00-b1b0-11eb-9cd3-6df983d7d3af.png)

Closing this issue as of now
